" Source file with plugins
source $HOME/.vim/config/plugins.vim

" Source file with settings
source $HOME/.vim/config/settings.vim

" Source file with mappings
source $HOME/.vim/config/mappings.vim

" Source file with highlighting
source $HOME/.vim/config/highlights.vim

" To see definition in python or bash type K(shift + k) under cursor in normal mode.

" Source file with colorscheme
source $HOME/.vim/config/colorscheme.vim

" Source file with autocommands
source $HOME/.vim/config/autocommands.vim
